In [2]:
import pandas as pd

df = pd.read_parquet("data_hitech_day.parquet")

In [3]:
df2 = pd.read_parquet("data_hitech_month.parquet")

In [4]:
df2.head().T

,0,1,2,3,4
cus_id,"{'member0': 4110769.0, 'member1': None}","{'member0': 4110774.0, 'member1': None}","{'member0': 4110777.0, 'member1': None}","{'member0': 4110779.0, 'member1': None}","{'member0': 4110850.0, 'member1': None}"
p5_tongtien,16500.0,17335.238281,13000.0,5000.0,16500.0
p10_tongtien,16500.0,17999.0,13000.0,17333.333984,16500.0
p25_tongtien,16500.0,17999.0,26799.777344,19000.0,16500.0
p50_tongtien,21000.0,17999.0,35550.1875,28000.0,21501.0
p75_tongtien,22000.0,17999.0,66610.789062,28000.0,33002.0
p90_tongtien,22000.0,17999.0,175211.0,28000.0,33002.0
p95_tongtien,24000.0,17999.0,229744.0,28000.0,33002.0
tongdon_cao,5,1773,19,208,2
tongdon_thap,7,1827,20,157,2
sanluong_phat_yeucau,21.0,1943.0,189.0,388.0,5.0
khachhang_nhan,18,1504,181,303,4
khachhang_nhieudon,2,259,8,44,1
khachhang_moi,15.0,1174.0,154.0,265.0,2.0
khachhang_thangtruoc,10.0,1219.0,171.0,533.0,5.0
khachhang_quaylai,0.0,260.0,14.0,28.0,2.0
khachhang_roibo,10.0,959.0,157.0,505.0,3.0
partition,202511,202511,202511,202511,202511

In [8]:
df["ma_tinh_hoatdong_chinh"].unique()

array(['DNI', 'HNI', 'HPG', 'KTM', 'HCM', 'PHO', 'LCI', 'AGG', 'VLG',
       'LAN', 'YBN', 'QNM', 'THA', 'HDG', 'DNG', 'CTO', 'BTE', 'HYN',
       'HGG', 'QBH', 'HTH', 'STG', 'GLI', 'TBH', 'TGG', 'DLK', 'KHA',
       'DBN', 'CBG', 'QNI', 'TVH', 'NAN', 'VTU', 'BKN', 'SLA', 'CMU',
       'LDG', 'DKG', 'BLU', 'TQG', 'VPC', 'HBH', 'HNM', 'HUE', 'BGG',
       'KGG', 'LSN', 'QTI', 'QNH', 'BPC', 'LCU', 'TNN', 'NDH', 'BTN',
       'DTP', 'NBH', 'NTN', 'PYN', 'BDG', 'BDH'], dtype=object)

In [3]:
df2 = pd.read_parquet("data_hitech_month.parquet")

In [12]:
# Làm sạch cus_id: chuyển từ dict string sang giá trị member0
import ast

def extract_cus_id(cus_id_val):
    if isinstance(cus_id_val, dict):
        return cus_id_val.get('member0')
    elif isinstance(cus_id_val, str):
        try:
            d = ast.literal_eval(cus_id_val)
            return d.get('member0')
        except:
            return cus_id_val
    return cus_id_val

df["cus_id_clean"] = df["cus_id"].apply(extract_cus_id)
df_test = df.groupby(["cus_id_clean"]).agg({"ma_tinh_hoatdong_chinh": "nunique"}).reset_index()

In [13]:
df_test[df_test["ma_tinh_hoatdong_chinh"] > 1]

Empty DataFrame
Columns: [cus_id_clean, ma_tinh_hoatdong_chinh]
Index: []

In [3]:
df[df["ngay_sinh"] < 0]

,cus_id,ten_phuongxa_hoatdong_chinh,ten_quanhuyen_hoatdong_chinh,ma_tinh_hoatdong_chinh,tongdon_diaban_chinh,tong_tien,min_tongtien,max_tongtien,tong_don,avg_tongtien,...,lydo_hoan,so_donhoan_nhieunhat,lydo_khieunai,so_khieunai_nhieunhat,ngay_hoptac,ngay_sinh,ten_dangky,nganh_hang,loai_khachhang,partition
574,"{'member0': 3167023.0, 'member1': None}",PHƯỜNG TAM PHÚ,QUẬN THỦ ĐỨC,HCM,6,191502,19000,40500,6,31917.000000,...,None,NaN,NaN,NaN,04/05/2020,-6.019488e+11,CUA******,Khác,Hộ kinh doanh cá thể,20251208
1273,"{'member0': 3162933.0, 'member1': None}",PHƯỜNG TRUNG HÒA,QUẬN CẦU GIẤY,HNI,1,30000,30000,30000,1,30000.000000,...,None,NaN,NaN,NaN,12/03/2025,-3.290112e+11,Hạt******,"Ngành Mỹ phẩm , SP làm đẹp",Hộ kinh doanh cá thể,20251208
1421,"{'member0': 4126418.0, 'member1': None}",PHƯỜNG 10,QUẬN GÒ VẤP,HCM,18,444605,16500,35100,18,24700.277344,...,None,NaN,20.0,1.0,03/12/2023,-2.895264e+11,ngọc******,Khác,Cá nhân,20251208
1728,"{'member0': 4125645.0, 'member1': None}",PHƯỜNG HƯNG THẠNH,QUẬN CÁI RĂNG,CTO,7,126000,18000,18000,7,18000.000000,...,None,NaN,NaN,NaN,17/08/2025,-2.926368e+11,53.22.12.44******,None,Cá nhân,20251208
3014,"{'member0': 4120889.0, 'member1': None}",None,None,HNI,1,68104,68104,68104,1,68104.000000,...,None,NaN,NaN,NaN,27/05/2020,-2.857248e+11,ngô******,Khác,Hộ kinh doanh cá thể,20251208
3274,"{'member0': 4126983.0, 'member1': None}",THỊ TRẤN VÔI,HUYỆN LẠNG GIANG,BGG,8,170000,21000,23000,8,21250.000000,...,None,NaN,NaN,NaN,08/06/2024,-1.761696e+11,NGUYỄN******,Khác,Hộ kinh doanh cá thể,20251208
3929,"{'member0': 4121990.0, 'member1': None}",PHƯỜNG 2,QUẬN 10,HCM,3,101799,18600,45100,3,33933.000000,...,None,NaN,NaN,NaN,28/10/2025,-1.615680e+10,99******,None,None,20251208
4088,"{'member0': 4125825.0, 'member1': None}",None,None,HNI,2,342968,28000,314968,2,171484.000000,...,None,NaN,NaN,NaN,18/08/2021,-3.611520e+10,Lê******,Khác,Hộ kinh doanh cá thể,20251208
5143,"{'member0': 4113390.0, 'member1': None}",PHƯỜNG LINH XUÂN,THÀNH PHỐ THỦ ĐỨC,HCM,2,60500,16500,44000,2,30250.000000,...,None,NaN,NaN,NaN,30/12/2018,-1.495584e+11,A******,Khác,Hộ kinh doanh cá thể,20251208
5273,"{'member0': 4116621.0, 'member1': None}",PHƯỜNG YÊN HÒA,QUẬN CẦU GIẤY,HNI,2,76501,16500,31000,3,25500.333984,...,None,NaN,NaN,NaN,15/05/2025,-3.557088e+11,Phạm******,None,Hộ kinh doanh cá thể,20251208
5476,"{'member0': 14558227.0, 'member1': None}",XÃ LỘC AN,HUYỆN BẢO LÂM,LDG,12,526227,13000,97491,12,43852.250000,...,None,NaN,NaN,NaN,04/02/2025,-7.897824e+11,Hoa******,Bán lẻ,Hộ kinh doanh cá thể,20251208
5540,"{'member0': 14130189.0, 'member1': None}",PHƯỜNG 9,QUẬN GÒ VẤP,HCM,4,140500,18000,45500,4,35125.000000,...,KHÁCH HÀNG KHÔNG TRẢ TIỀN K LẤY HOÀN ĐƠN,1.0,NaN,NaN,16/02/2023,-6.912000e+09,Hồng******,Khác,Cá nhân,20251208
6558,"{'member0': 3167922.0, 'member1': None}",PHƯỜNG LONG BÌNH TÂN,THÀNH PHỐ BIÊN HÒA,DNI,1,30000,30000,30000,1,30000.000000,...,None,NaN,NaN,NaN,16/09/2018,-4.043520e+10,Trinh******,None,Cá nhân,20251208
6743,"{'member0': 3161899.0, 'member1': None}",THỊ TRẤN EA KNỐP,HUYỆN EA KAR,DLK,1,75000,75000,75000,1,75000.000000,...,None,NaN,NaN,NaN,31/12/2018,-5.503680e+10,Diễm******,None,Cá nhân,20251208
6774,"{'member0': 3161614.0, 'member1': None}",PHƯỜNG KHƯƠNG THƯỢNG,QUẬN ĐỐNG ĐA,HNI,1,41999,41999,41999,1,41999.000000,...,None,NaN,NaN,NaN,24/09/2018,-3.319488e+11,Thương******,Khác,Cá nhân,20251208
8258,"{'member0': 4124977.0, 'member1': None}",PHƯỜNG QUỐC TỬ GIÁM,QUẬN ĐỐNG ĐA,HNI,64,2713022,26500,204008,64,42390.968750,...,None,NaN,57.0,1.0,15/07/2025,-1.234656e+11,Bồ******,None,Hộ kinh doanh cá thể,20251208
8352,"{'member0': 4126732.0, 'member1': None}",PHƯỜNG BỬU LONG,THÀNH PHỐ BIÊN HÒA,DNI,2,403610,37000,366610,2,201805.000000,...,None,NaN,NaN,NaN,02/08/2018,-7.361280e+10,HOA******,Khác,Hộ kinh doanh cá thể,20251208
8875,"{'member0': 4123210.0, 'member1': None}",PHƯỜNG TÂN BIÊN,THÀNH PHỐ BIÊN HÒA,DNI,1,62099,62099,62099,1,62099.000000,...,None,NaN,NaN,NaN,01/06/2018,-3.961440e+11,Thanh******,Khác,Hộ kinh doanh cá thể,20251208

In [4]:
df["thu_ho"]

0             0.0
1        140000.0
2             NaN
3             0.0
4             NaN
          ...
9995     248000.0
9996          0.0
9997          NaN
9998          NaN
9999    1905000.0
Name: thu_ho, Length: 10000, dtype: float64

In [5]:
df.tail(5)

,cus_id,ten_phuongxa_hoatdong_chinh,ten_quanhuyen_hoatdong_chinh,ma_tinh_hoatdong_chinh,tongdon_diaban_chinh,tong_tien,min_tongtien,max_tongtien,tong_don,avg_tongtien,...,lydo_hoan,so_donhoan_nhieunhat,lydo_khieunai,so_khieunai_nhieunhat,ngay_hoptac,ngay_sinh,ten_dangky,nganh_hang,loai_khachhang,partition
9995,"{'member0': 3170284.0, 'member1': None}",None,None,HNI,9,317000,16500,43001,9,35222.222656,...,None,NaN,NaN,NaN,02/02/2018,4.685220e+11,Thanh******,Quần áo & Phụ kiện,Hộ kinh doanh cá thể,20251208
9996,"{'member0': 3170286.0, 'member1': None}",PHƯỜNG HÒA THỌ ĐÔNG,QUẬN CẨM LỆ,DNG,22,470371,16500,71870,22,21380.500000,...,None,NaN,NaN,NaN,30/10/2019,NaN,Lục******,Khác,Hộ kinh doanh cá thể,20251208
9997,"{'member0': 3170288.0, 'member1': None}",PHƯỜNG 14,QUẬN GÒ VẤP,HCM,1,127000,127000,127000,1,127000.000000,...,None,NaN,NaN,NaN,16/07/2024,NaN,Nguyễn******,None,Cá nhân,20251208
9998,"{'member0': 3170293.0, 'member1': None}",PHƯỜNG HIỆP BÌNH PHƯỚC,THÀNH PHỐ THỦ ĐỨC,HCM,1,53000,53000,53000,1,53000.000000,...,None,NaN,NaN,NaN,15/04/2019,NaN,Thái******,Khác,Hộ kinh doanh cá thể,20251208
9999,"{'member0': 3170295.0, 'member1': None}",None,None,HNI,1,45000,45000,45000,1,45000.000000,...,None,NaN,NaN,NaN,25/08/2023,NaN,Lê******,None,Hộ kinh doanh cá thể,20251208

In [6]:
df["ngay_hoptac"].value_counts()

ngay_hoptac
28/09/2017    213
08/12/2025    127
16/01/2019     92
15/01/2019     65
27/12/2018     34
             ...
23/08/2019      1
02/09/2023      1
26/04/2022      1
12/12/2021      1
02/02/2018      1
Name: count, Length: 2476, dtype: int64